resources:
  - ./../base
  - ./ingress.yaml
namePrefix: prod-
images:
  - name: tylermarques-com
    newName: ghcr.io/tylermarques/tylermarques-com
    newTag: 6b90eec228bc38a8b8b5613530fe53a3e93a58cb
