resources:
  - ./../base
  - ./ingress.yaml
namePrefix: prod-
namespace: u-the-bomb-com-prod
images:
  - name: u-the-bomb-com
    newName: ghcr.io/tylermarques/u-the-bomb-com
    newTag: 7a90b5bf9807a81a712c8a49df5487c68651f650
