resources:
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - directory-watcher-deployment.yaml
  - diarization-worker-deployment.yaml
# secretGenerator:
#   - name: meeting-tools-secrets
#     literals:
#       - hugginface=
#       - jwt=

